### ISSUE TITLE
 Unable to create call adapter for c.g<com.judopay.model.Receipt>  for method JudoApiService.preAuth

### ISSUE THREAD

**Issue by SaikCaskey** [Judopay/Android-Sample-App#2]
Judo has suddenly stopped allowing me to add a card!
The Progress bar shows up, does some work, then disappears without any message
There's a null pointer warning right before - is this breaking the request? I don't use device DNA explicitly, this is just a PreAuth fragment 

Stack trace:
05-26 11:58:45.101 26559-26559/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1626)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1573)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:197)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:258)
05-26 11:58:45.101 26559-26559/? W/System.err:     at com.judopay.devicedna.signal.c$1.a(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at com.judopay.devicedna.signal.c$1.call(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$11.a(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$11.call(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$1.a(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$1.call(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$6.a(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$6.call(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g.b(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g.a(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.g$5$1.call(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at c.a.b.b$b.run(Unknown Source)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-26 11:58:45.101 26559-26559/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7325)
05-26 11:58:45.101 26559-26559/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-26 11:58:45.101 26559-26559/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-26 11:58:45.101 26559-26559/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-26 11:58:45.141 26559-26559/? E/Judopay: Error calling Judopay API
                                            java.lang.IllegalArgumentException: Unable to create call adapter for c.g<com.judopay.model.Receipt>
                                                for method JudoApiService.preAuth
                                                at retrofit2.ServiceMethod$Builder.methodError(Unknown Source)
                                                at retrofit2.ServiceMethod$Builder.createCallAdapter(Unknown Source)
                                                at retrofit2.ServiceMethod$Builder.build(Unknown Source)
                                                at retrofit2.Retrofit.loadServiceMethod(Unknown Source)
                                                at retrofit2.Retrofit$1.invoke(Unknown Source)
                                                at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                at $Proxy12.preAuth(Unknown Source)
                                                at com.judopay.e$1$1.a(Unknown Source)
                                                at com.judopay.e$1$1.call(Unknown Source)
                                                at c.d.a.m$a.onNext(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.g$1$1.a(Unknown Source)
                                                at c.g$4.onNext(Unknown Source)
                                                at c.f.a.onNext(Unknown Source)
                                                at c.d.a.p$2$1.onNext(Unknown Source)
                                                at c.d.d.j$d.request(Unknown Source)
                                                at c.d.b.a.a(Unknown Source)
                                                at c.d.a.p$2$1.setProducer(Unknown Source)
                                                at c.d.d.j$a.a(Unknown Source)
                                                at c.d.d.j$a.call(Unknown Source)
                                                at c.c.a(Unknown Source)
                                                at c.d.a.p$2.onError(Unknown Source)
                                                at c.g$1$1.a(Unknown Source)
                                                at c.g$12$1.a(Unknown Source)
                                                at c.g$4.onError(Unknown Source)
                                                at c.f.a.a(Unknown Source)
                                                at c.f.a.onError(Unknown Source)
                                                at c.d.a.m$a.onError(Unknown Source)
                                                at c.d.a.m$a.onNext(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.g$1$1.a(Unknown Source)
                                                at c.g$4.onNext(Unknown Source)
                                                at c.f.a.onNext(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.g$1$1.a(Unknown Source)
                                                at c.d.d.k$1.a(Unknown Source)
                                                at c.d.d.k$1.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$12$1.a(Unknown Source)
                                                at c.g$12$1.a(Unknown Source)
                                                at c.g$4.onNext(Unknown Source)
                                                at c.f.a.onNext(Unknown Source)
                                                at c.d.a.m$a.onNext(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.g$1$1.a(Unknown Source)
                                                at c.g$4.onNext(Unknown Source)
                                                at c.f.a.onNext(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.d.b.b.a(Unknown Source)
                                                at c.g$1$1.a(Unknown Source)
                                                at c.d.a.i$1.onCompleted(Unknown Source)
                                                at c.f.b.onCompleted(Unknown Source)
                                                at c.f.c.onCompleted(Unknown Source)
                                                at c.d.a.d$c.a(Unknown Source)
                                                at c.d.a.d$c.onCompleted(Unknown Source)
                                                at c.d.a.e$a.a(Unknown Source)
                                                at c.d.a.e$a.request(Unknown Source)
                                                at c.i.setProducer(Unknown Source)
                                                at c.d.a.e.a(Unknown Source)
                                                at c.d.a.e.call(Unknown Source)
                                                at c.c.a(Unknown Source)
                                                at c.d.a.d.a(Unknown Source)
                                                at c.d.a.d.call(Unknown Source)
                                                at c.c.a(Unknown Source)
                                                at c.d.a.i.a(Unknown Source)
                                                at c.d.a.i.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$9.a(Unknown Source)
                                                at c.g$9.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g$6.a(Unknown Source)
                                                at c.g$6.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$12.a(Unknown Source)
                                                at c.g$12.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g$6.a(Unknown Source)
                                                at c.g$6.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$12.a(Unknown Source)
                                                at c.g$12.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g$6.a(Unknown Source)
                                                at c.g$6.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$9.a(Unknown Source)
                                                at c.g$9.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g$6.a(Unknown Source)
                                                at c.g$6.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$12.a(Unknown Source)
                                                at c.g$12.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                                at c.g.a(Unknown Source)
                                                at c.g$9.a(Unknown Source)
                                                at c.g$9.call(Unknown Source)
                                                at c.g$1.a(Unknown Source)
                                                at c.g$1.call(Unknown Source)
                                                at c.g.b(Unknown Source)
                                            	at c

**Comment by SaikCaskey** [comment]
Just updated all my dependencies relating to this, it wasn't your guys' fault!!
